; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]

platform=espressif32
board=esp32dev
framework=arduino

lib_deps =
    knolleary/PubSubClient
    https://github.com/tzapu/WiFiManager

build_flags =
    -D DELAY_COUCOU=2
    -D DEBUG_SPEED=${common.monitor_speed}

monitor_speed = 115200

[env:OLED_APPAIRAGE]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

build_flags = 
    ${common.build_flags}
     -D D_OLED=1

upload_port = COM5
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0

[env:OLED_LESS_APPAIRAGE]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}

build_flags = 
    ${common.build_flags}

upload_port = COM5
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0

[env:OLED_DHT-Debug]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

build_flags = 
    ${common.build_flags}
     -D D_OLED=1
     -D D_DHT=1
     -D DEBUG=1

upload_port = COM5
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0


[env:OLED_DHT]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

build_flags = 
    ${common.build_flags}
     -D D_OLED=1
     -D D_DHT=1

upload_port = COM5
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0

[env:MOVEMENT]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
    5orenso/PirSensor @ ^1.0.1
build_flags = 
    ${common.build_flags}
     -D D_MOVEMENT=1

upload_port = COM6
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0


[env:MOVEMENT-Debug]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
lib_deps = ${common.lib_deps}
    5orenso/PirSensor @ ^1.0.1
build_flags = 
    ${common.build_flags}
     -D D_MOVEMENT=1
     -D DEBUG=1

upload_port = COM6
monitor_speed = ${common.monitor_speed}
#monitor_dtr = 0
#monitor_rts = 0